config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from pages.views import home
from sections.views import page

urlpatterns = [
    path("", home, name="home"),
    path("page/", page, name="page"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sallve.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sallve/users/urls.py
from django.urls import path

from sallve.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pages/models.py
from django.db import models


class Page(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    image = models.ImageField(blank=True, upload_to='images/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

sallve/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for sallve.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

sections/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.contrib.auth import get_user_model
from pages.models import Page


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = RichTextField()
    video = models.CharField(max_length=255, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Gallery(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE, related_name='gallery')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.post.title

sallve/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

pages/views.py
from django.shortcuts import render
from pages.models import Page


# Create your views here.
def home(request):
    order_page = request.GET.get('order', 'recent')
    if order_page == 'old':
        pages = Page.objects.all()
    else:
        pages = Page.objects.all().order_by('-created')

    return render(request, 'pages/home.html', {'pages': pages})

sallve/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

sections/views.py
from django.shortcuts import render, redirect
from sections.models import Post, Gallery


# Create your views here.
def page(request):
    id = request.GET.get('id', None)

    if not id:
        return redirect('home')

    try:
        id = int(id)
    except ValueError:
        return redirect('home')

    order_page = request.GET.get('order', 'recent')
    if order_page == 'old':
        posts = Post.objects.filter(page_id=id).all()
    else:
        posts = Post.objects.filter(page_id=id).all().order_by('-created')

    image = posts[0].page.image
    title = posts[0].page.title
    return render(request, 'sections/inner_pages.html', {'posts': posts, 'title': title, 'image': image, 'page_id': id})

sallve/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}sallve{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Conhecendo a estrutura do Django">
    <meta name="author" content="Weverton">

    {% block css %}
      <link href="{% static 'css/home.css' %}" rel="stylesheet">
    {% endblock %}
  </head>

  <body>
    {% block header %}{% endblock %}
    {% block nav %}{% endblock %}
    {% block main %}{% endblock %}

    {% block javascript %}
    {% endblock %}
  </body>
</html>

sallve/templates/pages/about.html
{% extends "base.html" %}

sallve/templates/pages/home.html
{% extends "base.html" %}

{% block header %}
    <header>
        <h1>BLOG DA SALLVE</h1>
    </header>
{% endblock %}

{% block main %}
    <main>
        <div class="select">
            <select name="order" onchange="location=this.value">
                <option selected disabled>Order by</option>
                <option value="{% url 'home' %}?order=recent">Recent</option>
                <option value="{% url 'home' %}?order=old">Old</option>
            </select>
        </div>

        <div class="l-cards">
            {% for page in pages %}
                <a class="c-card" href="{% url 'page' %}?id={{page.id}}">
                    <div class="c-card__image">
                        <img src="{{ page.image.url }}" alt="{{ page.title }}">
                    </div>

                    <div class="c-card_content">
                        <span>{{ page.title }}</span>
                    </div>
                </a>
            {% endfor %}
            
        </div>
    </main>
{% endblock %}

sallve/templates/sections/inner_pages.html
{% extends "base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick/slick-theme.css' %}"/>

    <link href="{% static 'css/inner_pages.css' %}" rel="stylesheet">
{% endblock %}


{% block header %}
    <header>
        <div class="c-box">
            <img src="{{ image.url }}" alt="{{ page.title }}" class="c-box__img">
        </div>
        <h1>{{ title }}</h1>
    </header>
{% endblock %}

{% block nav %}
    <nav>
        <h2>Menu</h2>
        {% for post in posts %}
            <a href="#{{ post.id }}">
                <p>{{ post.title }}</p>
                <svg width="24" height="24" viewBox="0 0 24 24" fill="black" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M17.1716 13L10.8787 19.2929L12.2929 20.7071L21 12L12.2929 3.29291L10.8787 4.70712L17.1716 11H2.58579V13H17.1716Z" fill="white"/>
                </svg>
            </a>
        {% endfor %}
    </nav>
{% endblock %}

{% block main %}
    <main>
        {% for post in posts %}
        <h2>{{ post.title }}</h2>
        <div class="c-card-post" id="{{ post.id }}">
            <div class="c-card-post__image js-card-post__image">
                {% for photo in post.gallery.all %}
                    <img src="{{ photo.image.url }}" alt="{{ post.title }}">
                {% endfor %}
            </div>
            {% if post.url_video %}
                <div class="c-card-post__video">
                    {{ post.url_video | safe }}
                </div>
            {% endif %}
            <div class="c-card-post__content">
                {{ post.content | safe }}
            </div>
        </div>
        {% endfor %}
    </main>
{% endblock %}


{% block javascript %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'slick/slick/slick.min.js' %}"></script>

    <script>
        $('.js-card-post__image').slick({
            dots: true,
            infinite: true,
            speed: 500,
            fade: true,
            cssEase: 'linear'
        });
    </script>
{% endblock %}

sallve/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

sallve/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}